// <auto-generated />
namespace WebBanHang_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class capnhatsp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(capnhatsp));
        
        string IMigrationMetadata.Id
        {
            get { return "202002201609366_capnhatsp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
